#!/usr/bin/env python3
"""
Solare — build small local font files.

Downloads only what the site uses:
  - Poppins (Latin) in the 5 weights used
  - Noto Serif JP and Noto Sans Sinhala cut down to the exact characters found in public/
Run again if you add new Japanese or Sinhala text:   python3 tools/fonts.py
"""
import re, pathlib, urllib.request, urllib.parse

ROOT = pathlib.Path(__file__).resolve().parent.parent
PUB = ROOT / "public"
OUT = PUB / "assets" / "fonts"
UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36"

def get(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": UA}), timeout=60).read()

text = "".join(p.read_text(encoding="utf-8") for p in
               [PUB / "index.html", PUB / "assets/data.js", PUB / "assets/css/style.css", PUB / "assets/js/main.js"])
jp = "".join(sorted(set(re.findall(r"[　-ヿ一-鿿＀-￯]", text))))
si = "".join(sorted(set(re.findall(r"[඀-෿‍]", text))))
print(f"Japanese chars: {len(jp)}  Sinhala chars: {len(si)}")

css_out = ["/* Generated by tools/fonts.py — do not edit by hand */"]

def faces(family, weights, text_param=None, keep=None):
    url = f"https://fonts.googleapis.com/css2?family={family.replace(' ', '+')}:wght@{';'.join(map(str, weights))}&display=swap"
    if text_param:
        url += "&text=" + urllib.parse.quote(text_param)
    css = get(url).decode()
    files = {}                                   # font bytes -> (weights, unicode-range)
    for label, body in re.findall(r"(?:/\*\s*([\w-]+)\s*\*/\s*)?@font-face\s*{([^}]*)}", css):
        if keep and label and label not in keep:
            continue
        weight = int(re.search(r"font-weight:\s*(\d+)", body).group(1))
        data = get(re.search(r"url\((https://[^)]+)\)", body).group(1))
        rng = re.search(r"unicode-range:\s*([^;]+);", body)
        files.setdefault(data, ([], rng.group(1) if rng and not text_param else None))[0].append(weight)
    for data, (ws, rng) in files.items():        # identical files (variable fonts) are stored once
        slug = family.lower().replace(" ", "-")
        name = f"{slug}-{ws[0]}.woff2" if len(ws) == 1 else f"{slug}.woff2"
        (OUT / name).write_bytes(data)
        print(f"  {name}: {len(data) / 1024:.1f} KB")
        wt = str(ws[0]) if len(ws) == 1 else f"{min(ws)} {max(ws)}"
        css_out.append(
            f"@font-face{{font-family:\"{family}\";font-style:normal;font-weight:{wt};font-display:swap;"
            f"src:url(\"../fonts/{name}\") format(\"woff2\");" + (f"unicode-range:{rng};" if rng else "") + "}")

OUT.mkdir(parents=True, exist_ok=True)
for old in OUT.glob("*.woff2"):
    if not old.name.startswith("fa-"):
        old.unlink()
faces("Poppins", [400, 500, 600, 700, 800], keep={"latin"})
faces("Noto Serif JP", [500, 700], text_param=jp)
faces("Noto Sans Sinhala", [700], text_param=si)
(PUB / "assets/css/fonts.css").write_text("\n".join(css_out) + "\n", encoding="utf-8")
print("Wrote assets/css/fonts.css")
