#!/usr/bin/env python3
"""
Solare — build a small Font Awesome file with only the icons the site uses.

Scans public/ and build.js for "fa-..." names, then cuts the Font Awesome Free fonts
down to those icons. Run again after adding a new icon:   python3 tools/icons.py
Font Awesome Free 6.5.2 — icons CC BY 4.0, fonts SIL OFL 1.1 (fontawesome.com/license/free)
"""
import io, re, pathlib, urllib.request
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
PUB = ROOT / "public"
CDN = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2"
get = lambda u: urllib.request.urlopen(urllib.request.Request(u, headers={"User-Agent": "Mozilla/5.0"}), timeout=60).read()

sources = [PUB / "index.html", PUB / "assets/data.js", PUB / "assets/js/main.js", PUB / "assets/css/style.css", ROOT / "build.js"]
text = "".join(p.read_text(encoding="utf-8") for p in sources)
names = sorted(set(re.findall(r"\bfa-([a-z0-9]+(?:-[a-z0-9]+)*)", text)) - {"solid", "brands", "regular"})
codes = {f"{int(c, 16):04x}" for c in re.findall(r'content:\s*"\\(f[0-9a-f]{3})"', text)}   # icons used directly in CSS

fa_css = get(CDN + "/css/all.min.css").decode()
cp = {}
for sel, code in re.findall(r'([^{}]+)\{content:"\\([0-9a-f]+)"\}', fa_css):
    for n in re.findall(r"\.fa-([a-z0-9-]+):before", sel):
        cp[n] = code
missing = [n for n in names if n not in cp]
if missing:
    raise SystemExit(f"Unknown icons: {missing}")

def cut(file, family_codes, out):
    font = TTFont(io.BytesIO(get(f"{CDN}/webfonts/{file}")))
    have = set(font.getBestCmap())
    want = [int(c, 16) for c in family_codes if int(c, 16) in have]
    opts = subset.Options(); opts.flavor = "woff2"; opts.layout_features = ["*"]; opts.notdef_outline = True
    s = subset.Subsetter(opts); s.populate(unicodes=want); s.subset(font)
    font.flavor = "woff2"; font.save(PUB / "assets/fonts" / out)
    return {f"{c:04x}" for c in want}

all_codes = {cp[n] for n in names} | codes
solid = cut("fa-solid-900.woff2", all_codes, "fa-solid.woff2")
brands = cut("fa-brands-400.woff2", all_codes - solid, "fa-brands.woff2")

css = ["/* Font Awesome Free 6.5.2 subset — generated by tools/icons.py (fontawesome.com/license/free) */",
       '@font-face{font-family:"Font Awesome 6 Free";font-style:normal;font-weight:900;font-display:block;src:url("../fonts/fa-solid.woff2") format("woff2")}',
       '@font-face{font-family:"Font Awesome 6 Brands";font-style:normal;font-weight:400;font-display:block;src:url("../fonts/fa-brands.woff2") format("woff2")}',
       ".fa-solid,.fa-brands{-moz-osx-font-smoothing:grayscale;-webkit-font-smoothing:antialiased;display:inline-block;font-style:normal;font-variant:normal;line-height:1;text-rendering:auto}",
       '.fa-solid{font-family:"Font Awesome 6 Free";font-weight:900}',
       '.fa-brands{font-family:"Font Awesome 6 Brands";font-weight:400}']
css += [f'.fa-{n}:before{{content:"\\{cp[n]}"}}' for n in names]
(PUB / "assets/css/icons.css").write_text("\n".join(css) + "\n", encoding="utf-8")
for f in ("fa-solid.woff2", "fa-brands.woff2"):
    print(f"  {f}: {(PUB / 'assets/fonts' / f).stat().st_size / 1024:.1f} KB")
print(f"{len(names)} icons ({len(solid)} solid, {len(brands)} brands) -> assets/css/icons.css")
